import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getDatabase, ref, set, onValue, get, onDisconnect } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getDatabase(app),$=s=>document.querySelector(s),roomId=new URLSearchParams(location.search).get("room");if(!roomId){document.body.innerHTML='<main class="glass mobile-card"><h2>找不到房號</h2><p>請重新掃描大螢幕上的 QR Code。</p></main>';throw new Error("Missing room")}
$("#roomLabel").textContent=roomId;let playerId=sessionStorage.getItem(`party_player_${roomId}`)||null,playerName=sessionStorage.getItem(`party_name_${roomId}`)||"",currentIndex=-1,votedIndex=null;const show=id=>["join","waiting","vote","end"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id));const makeId=()=>crypto?.randomUUID?crypto.randomUUID():`p_${Date.now()}_${Math.random().toString(36).slice(2,9)}`;if(playerId&&playerName){$("#welcome").textContent=`歡迎 ${playerName}`;show("waiting")}
$("#joinBtn").addEventListener("click",joinGame);$("#nameInput").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();joinGame()}});async function joinGame(){const name=$("#nameInput").value.trim().slice(0,12);if(!name){$("#joinMsg").textContent="請先輸入名字";return}const m=await get(ref(db,`rooms/${roomId}/meta`));if(!m.exists()){$("#joinMsg").textContent="房間不存在，請重新掃描 QR Code";return}if(m.val().status!=="waiting"){$("#joinMsg").textContent="這局已開始，請等待下一局";return}playerId=makeId();playerName=name;sessionStorage.setItem(`party_player_${roomId}`,playerId);sessionStorage.setItem(`party_name_${roomId}`,playerName);const pr=ref(db,`rooms/${roomId}/players/${playerId}`);await set(pr,{name:playerName,score:0,isAI:false,joinedAt:Date.now()});onDisconnect(pr).remove();$("#welcome").textContent=`歡迎 ${playerName}`;show("waiting")}
onValue(ref(db,`rooms/${roomId}/meta`),async s=>{const m=s.val();if(!m)return;if(m.status==="waiting"&&playerId){$("#waitText").textContent="請看著大螢幕，等待主持人開始。";show("waiting")}if(m.status==="playing"&&playerId){currentIndex=Number(m.currentIndex);await renderVote(m)}if(m.status==="ended"&&playerId){const p=(await get(ref(db,`rooms/${roomId}/players/${playerId}`))).val();$("#myScore").textContent=p?`${p.score||0} 分`:"遊戲結束";show("end")}});
async function renderVote(m){const q=(await get(ref(db,`rooms/${roomId}/questions/${currentIndex}`))).val();if(!q)return;$("#mobileProgress").textContent=`第 ${currentIndex+1} / ${m.questionCount} 題`;$("#mobileQuestion").textContent=q.question;$("#voteA").textContent=`A\n${q.A}`;$("#voteB").textContent=`B\n${q.B}`;$("#voteA").classList.remove("selected");$("#voteB").classList.remove("selected");$("#voteA").disabled=false;$("#voteB").disabled=false;$("#voteMsg").textContent="請選擇 A 或 B";const ex=await get(ref(db,`rooms/${roomId}/votes/${currentIndex}/${playerId}`));if(ex.exists())lockVote(ex.val().choice);else votedIndex=null;show("vote")}
async function cast(choice){if(!playerId||votedIndex===currentIndex)return;const vr=ref(db,`rooms/${roomId}/votes/${currentIndex}/${playerId}`);const ex=await get(vr);if(ex.exists()){lockVote(ex.val().choice);return}await set(vr,{choice,at:Date.now()});lockVote(choice)}function lockVote(c){votedIndex=currentIndex;$("#voteA").disabled=true;$("#voteB").disabled=true;(c==="A"?$("#voteA"):$("#voteB")).classList.add("selected");$("#voteMsg").textContent=`✅ 已選擇 ${c}`}$("#voteA").addEventListener("click",()=>cast("A"));$("#voteB").addEventListener("click",()=>cast("B"));
