import { initializeApp } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import { getDatabase, ref, set, update, onValue, get, remove } from "https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js";
import { buildQuestionSet } from "./questions.js";
import { buildQuestionSet } from "./questions.js";
const app=initializeApp(firebaseConfig),db=getDatabase(app),$=s=>document.querySelector(s),params=new URLSearchParams(location.search);
const randomRoom=()=>Array.from({length:5},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join("");
let roomId=params.get("room")||randomRoom();if(!params.get("room")){const u=new URL(location.href);u.searchParams.set("room",roomId);history.replaceState({},"",u)}
$("#roomCode").textContent=roomId;const roomRef=ref(db,`rooms/${roomId}`),metaRef=ref(db,`rooms/${roomId}/meta`),playersRef=ref(db,`rooms/${roomId}/players`),votesRoot=ref(db,`rooms/${roomId}/votes`);let players={},meta={},selectedCategory="mixed",roundTimer=null,aiTimers=[],lastProcessedRound=null;const QUESTION_SECONDS=8;
const show=id=>["lobby","category","count","game","ranking"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id));
const basePath=()=>location.pathname.replace(/\/[^/]*$/,"/");const mobileUrl=`${location.origin}${basePath()}mobile.html?room=${encodeURIComponent(roomId)}`;$("#joinUrl").textContent=mobileUrl;new QRCode($("#qr"),{text:mobileUrl,width:220,height:220});
if(!(await get(metaRef)).exists())await set(metaRef,{status:"waiting",category:null,questionCount:0,currentIndex:-1,roundEndsAt:0,winner:null,createdAt:Date.now()});
onValue(playersRef,s=>{players=s.val()||{};const list=Object.entries(players);$("#playerCount").textContent=`${list.length} 人`;$("#players").innerHTML="";list.sort((a,b)=>(a[1].joinedAt||0)-(b[1].joinedAt||0)).forEach(([,p])=>{const e=document.createElement("span");e.className="pill"+(p.isAI?" ai":"");e.textContent=(p.isAI?"🤖 ":"👤 ")+p.name;$("#players").appendChild(e)})});
onValue(metaRef,s=>{meta=s.val()||{};if(meta.status==="waiting")show("lobby");if(meta.status==="playing"){show("game");renderQuestion();runCountdown();scheduleAIVotes()}if(meta.status==="ended"){show("ranking");renderRanking()}});
onValue(votesRoot,()=>{if(meta.status==="playing")renderVotes()});
$("#startBtn").addEventListener("click",()=>show("category"));document.querySelectorAll(".cat").forEach(b=>b.addEventListener("click",()=>{selectedCategory=b.dataset.cat;show("count")}));document.querySelectorAll(".cnt").forEach(b=>b.addEventListener("click",()=>startGame(selectedCategory,Number(b.dataset.count))));$("#newRoomBtn").addEventListener("click",()=>location.href=`${basePath()}index.html?room=${randomRoom()}`);$("#restartBtn").addEventListener("click",async()=>{clearTimers();await remove(votesRoot);const u={};Object.entries(players).forEach(([id,p])=>{if(p.isAI)u[`players/${id}`]=null;else u[`players/${id}/score`]=0});u["meta/status"]="waiting";u["meta/currentIndex"]=-1;u["meta/winner"]=null;u["questions"]=null;await update(roomRef,u)});
async function startGame(category,count){clearTimers();const cur=(await get(playersRef)).val()||{},humans=Object.entries(cur).filter(([,p])=>!p.isAI);let need=humans.length<3?3-humans.length:(humans.length%2===0?1:0);const ai=["AI 阿湯哥","AI 小安","AI Lulu","AI 阿哲","AI 瑪莉歐"],u={};Object.entries(cur).forEach(([id,p])=>{if(p.isAI)u[`players/${id}`]=null;else u[`players/${id}/score`]=0});for(let i=0;i<need;i++){const id=`ai_${Date.now()}_${i}`;u[`players/${id}`]={name:ai[i],score:0,isAI:true,joinedAt:Date.now()+i}}buildQuestionSet(category,count).forEach((q,i)=>u[`questions/${i}`]=q);u["votes"]=null;u["meta"]={status:"playing",category,questionCount:count,currentIndex:0,roundEndsAt:Date.now()+QUESTION_SECONDS*1000,winner:null,createdAt:meta.createdAt||Date.now()};lastProcessedRound=null;await update(roomRef,u)}
async function renderQuestion(){const idx=Number(meta.currentIndex??-1);if(idx<0)return;const q=(await get(ref(db,`rooms/${roomId}/questions/${idx}`))).val();if(!q)return;$("#progress").textContent=`第 ${idx+1} / ${meta.questionCount} 題`;$("#questionText").textContent=q.question;$("#answerA").textContent=q.A;$("#answerB").textContent=q.B;resetBoxes();renderVotes()}
async function renderVotes(){const idx=Number(meta.currentIndex??-1);if(idx<0)return;const v=(await get(ref(db,`rooms/${roomId}/votes/${idx}`))).val()||{},vals=Object.values(v),A=vals.filter(x=>x.choice==="A").length,B=vals.filter(x=>x.choice==="B").length,t=Math.max(1,A+B);$("#votesA").textContent=`${A} 票`;$("#votesB").textContent=`${B} 票`;$("#boxA").style.transform=`scale(${1+(A/t)*.13})`;$("#boxB").style.transform=`scale(${1+(B/t)*.13})`;if(meta.status==="playing"&&Object.keys(players).length>=3&&vals.length>=Object.keys(players).length)finishRound()}
function runCountdown(){clearInterval(roundTimer);const tick=()=>{const ms=Math.max(0,(meta.roundEndsAt||0)-Date.now());$("#timer").textContent=Math.ceil(ms/1000);$("#timerBar").style.width=`${Math.max(0,Math.min(100,ms/(QUESTION_SECONDS*1000)*100))}%`;if(ms<=0){clearInterval(roundTimer);finishRound()}};tick();roundTimer=setInterval(tick,250)}
function clearTimers(){clearInterval(roundTimer);aiTimers.forEach(clearTimeout);aiTimers=[]}function scheduleAIVotes(){aiTimers.forEach(clearTimeout);aiTimers=[];const idx=Number(meta.currentIndex??-1);if(idx<0)return;Object.entries(players).filter(([,p])=>p.isAI).forEach(([id],i)=>{aiTimers.push(setTimeout(async()=>{const vr=ref(db,`rooms/${roomId}/votes/${idx}/${id}`);if(!(await get(vr)).exists()&&meta.status==="playing"&&Number(meta.currentIndex)===idx)await set(vr,{choice:Math.random()<.5?"A":"B",at:Date.now(),ai:true})},700+i*550+Math.random()*350))})}
async function finishRound(){const idx=Number(meta.currentIndex??-1);if(idx<0||lastProcessedRound===idx||meta.status!=="playing")return;lastProcessedRound=idx;clearTimers();const ps=(await get(playersRef)).val()||{},vs=(await get(ref(db,`rooms/${roomId}/votes/${idx}`))).val()||{};for(const [id] of Object.entries(ps))if(!vs[id]){const c=Math.random()<.5?"A":"B";await set(ref(db,`rooms/${roomId}/votes/${idx}/${id}`),{choice:c,at:Date.now(),auto:true});vs[id]={choice:c}}const A=Object.values(vs).filter(v=>v.choice==="A").length,B=Object.values(vs).filter(v=>v.choice==="B").length,w=A>B?"A":"B",u={};for(const [id,p] of Object.entries(ps))if(vs[id]?.choice===w)u[`players/${id}/score`]=Number(p.score||0)+1;await update(roomRef,u);animateImpact(w);setTimeout(async()=>{const next=idx+1;if(next>=Number(meta.questionCount))await update(metaRef,{status:"ended",winner:w});else{lastProcessedRound=null;await update(metaRef,{status:"playing",currentIndex:next,winner:null,roundEndsAt:Date.now()+QUESTION_SECONDS*1000})}},1800)}
function resetBoxes(){["attack-a","attack-b","defeat-a","defeat-b"].forEach(c=>{$("#boxA").classList.remove(c);$("#boxB").classList.remove(c)});$("#boxA").style.opacity="1";$("#boxB").style.opacity="1";$("#status").textContent="等待玩家投票"}function animateImpact(w){const a=$("#app"),f=$("#flash");a.classList.remove("shake");f.classList.remove("go");void a.offsetWidth;a.classList.add("shake");f.classList.add("go");if(w==="A"){$("#boxA").classList.add("attack-a");$("#boxB").classList.add("defeat-b")}else{$("#boxB").classList.add("attack-b");$("#boxA").classList.add("defeat-a")}$("#status").textContent=`💥 ${w} 獲勝！多數派 +1 分`}
async function renderRanking(){const list=Object.entries((await get(playersRef)).val()||{}).sort((a,b)=>(b[1].score||0)-(a[1].score||0)),med=["🥇","🥈","🥉"];$("#rankList").innerHTML="";list.slice(0,3).forEach(([,p],i)=>{const r=document.createElement("div");r.className="rank";r.innerHTML=`<span style="font-size:28px">${med[i]}</span><span class="name"></span><strong></strong>`;r.children[1].textContent=p.name;r.children[2].textContent=`${p.score||0} 分`;$("#rankList").appendChild(r)})}
